name: Lighthouse

on: push

jobs:
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
        env:
          GATSBY_INDELO_API_URL: https://indelo-website-api-staging.herokuapp.com/contact-us
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v3
        with:
          configPath: "./lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
